#!/usr/bin/php
<?php

exec("git diff --cached --name-status --diff-filter=ACM", $output);

foreach ($output as $line) {
  $file = trim(substr($line, 1));
  $extension = pathinfo($fileName, PATHINFO_EXTENSION);

  if ($extension === "php") {
    $escaped = escapeshellarg($file);
    exec("php -l {$escaped}", $output, $return);

    if ($result != 0) {
        echo implode("\n", $output), "\n";
        exit(1);
    }

    $binary = "vendor/bin/php-cs-fixer";
    exec("{$binary} --using-cache=no fix {$file}");
    exec("git add {$file}");
  }
}

exit(0);
